language: node_js
node_js:
  - '16'  # Make sure this matches your Node.js version

script:
  - npm install
  - npm test -- --coverage

deploy:
  provider: firebase
  token:
    secure: 1//059t9SxcEtLXQCgYIARAAGAUSNwF-L9IrCz8SJ6hakKN041zkEoHA2vx431dMK2z1_16Bchai6WTVFsvtGYBqsyo0lG3DWT8S09I  # Replace this with your token
  skip_cleanup: true
  on:
    branch: master
